server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA: todas las rutas van a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Si más adelante quieres proxyear /api al backend, lo agregamos aquí:
    # location /api/ {
    #     proxy_pass http://backend:8080/;
    # }
}
