# Identificación del proyecto
sonar.projectKey=laboratorio-client
sonar.projectName=Laboratorio Client
sonar.projectVersion=1.0

# SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_ac887b3d3f86a0d5aa0d5101e8ff69db9dc1e693

# Código fuente
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info

# Exclusiones razonables (no rompen coverage)
sonar.exclusions= \
  **/node_modules/**, \
  **/*.d.ts, \
  **/*.js, \
  **/environments/**, \
  **/main.ts, \
  **/polyfills.ts
